# Generated by Django 6.0.6 on 2026-06-23 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free (Trial)'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20)),
                ('storage_used_mb', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
