# Generated by Django 6.0.6 on 2026-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_token_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
