# Generated by Django 6.0.6 on 2026-07-01 07:10

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_access_pin_event_qr_token_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plan_type',
            field=models.CharField(choices=[('free', 7), ('starter', 30), ('pro', 30), ('premium', 30)], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='VIPProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reference_embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('added_by_organizer_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_profiles', to='events.event')),
            ],
            options={
                'db_table': 'events_vipprofile',
                'indexes': [models.Index(fields=['event'], name='events_vipp_event_i_efa085_idx')],
            },
        ),
    ]
