# Generated by Django 6.0.6 on 2026-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_plan_type_vipprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='vipprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
