# Generated by Django 6.0.6 on 2026-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_plan_type_alter_vipprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipprofile',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
