# Generated by Django 6.0.6 on 2026-07-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_vipprofile_thumbnail_key'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE events_event ALTER COLUMN qr_token_active DROP NOT NULL;",
            reverse_sql="-- irreversible, no-op",
        ),
    ]
