# Generated by Django 6.0.6 on 2026-07-16 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_fix_qr_token_active_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20, unique=True)),
                ('max_photos', models.IntegerField()),
                ('max_storage_mb', models.IntegerField()),
                ('hd_downloads_included', models.IntegerField()),
                ('price_inr', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='access_pin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='qr_token_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='qr_token_expires_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vipprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
