# Generated by Django 6.0.6 on 2026-07-16 07:04

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_planlimit_remove_event_access_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('storage_key', models.CharField(max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Everyone'), ('restricted', 'VIP + Video-Access only')], default='restricted', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_videos', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAccessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('reference_embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('thumbnail_key', models.CharField(blank=True, max_length=255)),
                ('added_by_organizer_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_access_profiles', to='events.event')),
            ],
            options={
                'db_table': 'events_videoaccessprofile',
                'indexes': [models.Index(fields=['event'], name='events_vide_event_i_c9131c_idx')],
            },
        ),
    ]
