# Generated by Django 6.0.6 on 2026-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_guest_selfie_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='vip_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
