# Generated by Django 6.0.6 on 2026-07-16 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_planlimit_remove_event_access_pin_and_more'),
        ('guests', '0004_guest_is_vip_guest_vip_name'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_requests', to='events.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_requests', to='guests.guest')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_requests', to='photos.photo')),
            ],
        ),
    ]
