# Generated by Django 6.0.6 on 2026-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_videorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='has_video_access',
            field=models.BooleanField(default=False),
        ),
    ]
