# Generated by Django 6.0.6 on 2026-07-01 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0003_alter_guest_selfie_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightReel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('video_storage_key', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='queued')),
                ('music_track', models.CharField(default='default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest')),
            ],
        ),
    ]
