# Generated by Django 6.0.6 on 2026-06-29 14:28

import django.db.models.deletion
from pgvector.django import VectorExtension
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key_preview', models.CharField(blank=True, max_length=512)),
                ('storage_key_hd', models.CharField(blank=True, max_length=512)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('preview_size_kb', models.FloatField(default=0)),
                ('hd_size_kb', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('faces_detected_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('bbox_x', models.IntegerField()),
                ('bbox_y', models.IntegerField()),
                ('bbox_w', models.IntegerField()),
                ('bbox_h', models.IntegerField()),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('event', 'file_hash'), name='unique_photo_per_event_hash'),
        ),
    ]
